from opencompass.models.internal import  InternLM

models = [
    # dict(
    #     abbr="copernicus_7b_v0_0_1_fix_100",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.0.1_fix/100",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/copernicus_7b_v0_0_1.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="copernicus_7b_v0_0_1_fix_500",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.0.1_fix/500",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/copernicus_7b_v0_0_1.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="copernicus_7b_v0_0_1_fix_1000",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.0.1_fix/1000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/copernicus_7b_v0_0_1.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),


    # dict(
    #     abbr="copernicus_7b_v0_0_2_100",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.0.2/100",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/copernicus_7b_v0_0_2.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="copernicus_7b_v0_0_2_500",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.0.2/500",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/copernicus_7b_v0_0_2.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="copernicus_7b_v0_0_2_1000",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.0.2/1000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/copernicus_7b_v0_0_2.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),

    # dict(
    #     abbr="7B_llama_coder_python_4000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama_coder_python/4000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder_python.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="7B_llama_coder_python_6000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama_coder_python/6000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder_python.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),

    # dict(
    #     abbr="copernicus_1b_v0_0_1_25000",
    #     type=InternLM,
    #     model_type="LLAMA_TF32",
    #     path="s3://checkpoints_ssd_02/copernicus_1b_v0.0.1/25000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/V7.model',
    #     tokenizer_type='v7',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_1_9_9.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="copernicus_7b_v0_1_1_100",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.1.1/100",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_1.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="copernicus_7b_v0_1_1_500",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.1.1/500",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_1.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    #
    # dict(
    #     abbr="copernicus_7b_v0_2_1_100",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.2.1/100",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_2.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="copernicus_7b_v0_2_1_500",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.2.1/500",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_2.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),

    # dict(
    #     abbr="7B_llama_coder_python_8000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama_coder_python/8000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder_python.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    #
    # dict(
    #     abbr="7B_llama_coder_python_10000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama_coder_python/10000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder_python.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    #
    # dict(
    #     abbr="7B_llama_coder_2000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama2_coder_v3/2000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="7B_llama_coder_4000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama2_coder_v3/4000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="7B_llama_coder_6000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama2_coder_v3/6000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="7B_llama_coder_8000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama2_coder_v3/8000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="7B_llama_coder_10000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama2_coder_v3/10000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="7B_llama_coder_12000",
    #     type=InternLM,
    #     path="s3://checkpoints_ssd_02/songdemin/7B_llama2_coder_v3/12000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share/songdemin/code/train_internlm/",
    #     model_config="/mnt/petrelfs/chenkeyu1/train_internlm/configs/7B_llama_coder.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),

    dict(
        abbr="copernicus_7b_v0_2_1_1000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.2.1/1000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_2.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_2_1_1500",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.2.1/1500",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_2.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_2_1_2000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.2.1/2000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_2.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),

    dict(
        abbr="copernicus_7b_v0_3_1_1000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.3.1/1000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_2.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_3_1_2000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.3.1/2000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_2.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_3_1_3000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.3.1/3000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_2.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_3_1_4000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.3.1/4000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/chenkeyu1/program/opencompass/configs/models/model_configs/copernicus_7b_v0_0_2.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
]

