from opencompass.models import HuggingFaceCausalLM

models = [
    dict(
        type=HuggingFaceCausalLM,
        abbr='llama-13b',
        path="/mnt/petrelfs/chenkeyu1/models/evaluation/open_llama_7b/",
        # tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
        tokenizer_kwargs=dict(padding_side='left',
                              truncation_side='left',
                              use_fast=False,
                              ),
        max_out_len=100,
        max_seq_len=2048,
        batch_size=8,
        model_kwargs=dict(device_map='auto'),
        batch_padding=True,  # if false, inference with for-loop without batch padding
        run_cfg=dict(num_gpus=1, num_procs=1),
    ),
    #
    # dict(
    #     type=HuggingFaceCausalLM,
    #     abbr='llama-13b-lora',
    #     path="/mnt/petrelfs/chenkeyu1/models/llama/llama-13b-hf",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     peft_path="/mnt/petrelfs/chenkeyu1/models/collie/llama-13b/lora",
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=8,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=2, num_procs=1),
    # ),
    #
    # dict(
    #     abbr="llama-13b-adamw",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-13b/adamw/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=2, num_procs=1),
    # ),
    # dict(
    #     abbr="llama-13b-adan",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-13b/adan/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=2, num_procs=1),
    # ),
    # dict(
    #     abbr="llama-13b-lion",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-13b/lion/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=2, num_procs=1),
    # ),
    # dict(
    #     abbr="llama-13b-lomo_lr-0.003_grad-norm-1.0_epoch-3",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-13b/lomo_lr-0.003_grad-norm-1.0_epoch-3/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=2, num_procs=1),
    # ),
    # dict(
    #     abbr="llama-13b-lomo_lr-0.01_grad-norm-1.0_epoch-3",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-13b/lomo_lr-0.01_grad-norm-1.0_epoch-3/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=2, num_procs=1),
    # ),
    #
    # dict(
    #     abbr="lomo_lr-0.01_grad-norm-1.0_weight-decay-0.0_epoch-5_tp1_dp8_bs16",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-13b/lomo_lr-0.01_grad-norm-1.0_weight-decay-0.0_epoch-5_tp1_dp8_bs16/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=2, num_procs=1),
    # ),

    # dict(
    #     type=HuggingFaceCausalLM,
    #     abbr='llama-30b',
    #     path="/mnt/petrelfs/chenkeyu1/models/llama/llama-30b-hf",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=8,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),

    # dict(
    #     type=HuggingFaceCausalLM,
    #     abbr='llama-30b-lora',
    #     path="/mnt/petrelfs/chenkeyu1/models/llama/llama-30b-hf",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     peft_path="/mnt/petrelfs/chenkeyu1/models/collie/llama-30b/lora_lr-0.0003_epoch-3",
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=8,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),
    #
    # dict(
    #     abbr="llama-30b-adan_lr-2e-4_weight-decay-2e-2_epoch-2",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-30b/adan_lr-2e-4_weight-decay-2e-2_epoch-2/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),
    # dict(
    #     abbr="llama-30b-adan_lr-5e-05_weight-decay-0.02_epoch-3",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-30b/adan_lr-5e-05_weight-decay-0.02_epoch-3/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),
    # dict(
    #     abbr="llama-30b-lomo_lr-0.01_grad-norm-1.0_epoch-3",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-30b/lomo_lr-0.01_grad-norm-1.0_epoch-3/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),
    # dict(
    #     abbr="llama-30b-lomo_lr-0.01_grad-norm-1.0_weight-decay-0.0_epoch-3_tp4_dp1_bs32",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-30b/lomo_lr-0.01_grad-norm-1.0_weight-decay-0.0_epoch-3_tp4_dp1_bs32/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),

    # dict(
    #     type=HuggingFaceCausalLM,
    #     abbr='llama-65b',
    #     path="/mnt/petrelfs/chenkeyu1/models/llama/llama-65b-hf",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=8,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=8, num_procs=1),
    # ),
    #
    # dict(
    #     type=HuggingFaceCausalLM,
    #     abbr='llama-65b-lora',
    #     path="/mnt/petrelfs/chenkeyu1/models/llama/llama-65b-hf",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     peft_path="/mnt/petrelfs/chenkeyu1/models/collie/llama-65b/lora",
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=8,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=8, num_procs=1),
    # ),
    #
    # dict(
    #     type=HuggingFaceCausalLM,
    #     abbr='llama-30b',
    #     path="/mnt/petrelfs/chenkeyu1/models/llama/llama-30b-hf",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=8,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),
    #
    # dict(
    #     abbr="llama-30b-adamw",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-30b/adamw/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),

    # dict(
    #     abbr="llama-30b-lion_lr-3e-06_weight-decay-0.03_epoch-3",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-30b/lion_lr-3e-06_weight-decay-0.03_epoch-3/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),
    # dict(
    #     abbr="llama-30b-lion_lr-3e-6_weight-decay-0.03_epoch-2",
    #     type=HuggingFaceCausalLM,
    #     path="/mnt/petrelfs/chenkeyu1/models/collie/llama-30b/lion_lr-3e-6_weight-decay-0.03_epoch-2/",
    #     tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
    #     tokenizer_kwargs=dict(padding_side='left',
    #                           truncation_side='left',
    #                           use_fast=False,
    #                           ),
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     model_kwargs=dict(device_map='auto'),
    #     batch_padding=False,  # if false, inference with for-loop without batch padding
    #     run_cfg=dict(num_gpus=4, num_procs=1),
    # ),
]
