from opencompass.models import HuggingFaceCausalLM


models = [
#     dict(
#         type=HuggingFaceCausalLM,
#         # abbr='llama-2-7b-hf',
#         # path="meta-llama/Llama-2-7b-hf",
#         # tokenizer_path='meta-llama/Llama-2-7b-hf',
#         path="/mnt/petrelfs/chenkeyu1/models/collie/llama-7b/adamw/",
#         tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
#         tokenizer_kwargs=dict(padding_side='left',
#                               truncation_side='left',
#                               use_fast=False,
#                               ),
#         max_out_len=100,
#         max_seq_len=2048,
#         batch_size=8,
#         model_kwargs=dict(device_map='auto'),
#         batch_padding=False, # if false, inference with for-loop without batch padding
#         run_cfg=dict(num_gpus=1, num_procs=1),
#     ),
# dict(
#         type=HuggingFaceCausalLM,
#         # abbr='llama-2-7b-hf',
#         # path="meta-llama/Llama-2-7b-hf",
#         # tokenizer_path='meta-llama/Llama-2-7b-hf',
#         path="/mnt/petrelfs/chenkeyu1/models/collie/llama-7b/adan/",
#         tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
#         tokenizer_kwargs=dict(padding_side='left',
#                               truncation_side='left',
#                               use_fast=False,
#                               ),
#         max_out_len=100,
#         max_seq_len=2048,
#         batch_size=8,
#         model_kwargs=dict(device_map='auto'),
#         batch_padding=False, # if false, inference with for-loop without batch padding
#         run_cfg=dict(num_gpus=1, num_procs=1),
#     ),
# dict(
#         type=HuggingFaceCausalLM,
#         # abbr='llama-2-7b-hf',
#         # path="meta-llama/Llama-2-7b-hf",
#         # tokenizer_path='meta-llama/Llama-2-7b-hf',
#         path="/mnt/petrelfs/chenkeyu1/models/collie/llama-7b/lion/",
#         tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
#         tokenizer_kwargs=dict(padding_side='left',
#                               truncation_side='left',
#                               use_fast=False,
#                               ),
#         max_out_len=100,
#         max_seq_len=2048,
#         batch_size=8,
#         model_kwargs=dict(device_map='auto'),
#         batch_padding=False, # if false, inference with for-loop without batch padding
#         run_cfg=dict(num_gpus=1, num_procs=1),
#     ),
# dict(
#         type=HuggingFaceCausalLM,
#         # abbr='llama-2-7b-hf',
#         # path="meta-llama/Llama-2-7b-hf",
#         # tokenizer_path='meta-llama/Llama-2-7b-hf',
#         path="/mnt/petrelfs/chenkeyu1/models/collie/llama-7b/sophia/",
#         tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
#         tokenizer_kwargs=dict(padding_side='left',
#                               truncation_side='left',
#                               use_fast=False,
#                               ),
#         max_out_len=100,
#         max_seq_len=2048,
#         batch_size=8,
#         model_kwargs=dict(device_map='auto'),
#         batch_padding=False, # if false, inference with for-loop without batch padding
#         run_cfg=dict(num_gpus=1, num_procs=1),
#     ),
# dict(
#         type=HuggingFaceCausalLM,
#         # abbr='llama-2-7b-hf',
#         # path="meta-llama/Llama-2-7b-hf",
#         # tokenizer_path='meta-llama/Llama-2-7b-hf',
#         path="/mnt/petrelfs/chenkeyu1/models/collie/llama-7b/lomo/",
#         tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
#         tokenizer_kwargs=dict(padding_side='left',
#                               truncation_side='left',
#                               use_fast=False,
#                               ),
#         max_out_len=100,
#         max_seq_len=2048,
#         batch_size=8,
#         model_kwargs=dict(device_map='auto'),
#         batch_padding=False, # if false, inference with for-loop without batch padding
#         run_cfg=dict(num_gpus=1, num_procs=1),
#     ),

dict(
        type=HuggingFaceCausalLM,
        abbr='llama-7b-lora',
        # path="meta-llama/Llama-2-7b-hf",
        # tokenizer_path='meta-llama/Llama-2-7b-hf',
        path="/mnt/petrelfs/chenkeyu1/models/llama/llama-7b-hf",
        tokenizer_path='/mnt/petrelfs/chenkeyu1/models/collie/tokenizer/',
        peft_path="/mnt/petrelfs/chenkeyu1/models/collie/llama-7b/lora",
        tokenizer_kwargs=dict(padding_side='left',
                              truncation_side='left',
                              use_fast=False,
                              ),
        max_out_len=100,
        max_seq_len=2048,
        batch_size=8,
        model_kwargs=dict(device_map='auto'),
        batch_padding=False, # if false, inference with for-loop without batch padding
        run_cfg=dict(num_gpus=1, num_procs=1),
    ),
]
