from opencompass.models.internal import  InternLM

models = [
    # dict(
    #     abbr="further_llama_13B_math_yf_6000",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/further_llama_13B_math_yf/6000/",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share_data/shaoyunfan/train_internlm/",
    #     model_config="/mnt/petrelfs/share_data/shaoyunfan/train_internlm/configs/further_llama_13B_math_yf_eval.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=2, num_procs=2)
    # ),

    # dict(
    #     abbr="copernicus_7b_v0_4_1_1000",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.4.1/1000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/configs/copernicus_7b_v0.4.1.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="copernicus_7b_v0_4_1_2000",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.4.1/2000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/configs/copernicus_7b_v0.4.1.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),
    # dict(
    #     abbr="copernicus_7b_v0_4_1_3000",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/copernicus_7b_v0.4.1/3000",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
    #     model_config="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/configs/copernicus_7b_v0.4.1.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),

    # dict(
    #     abbr="llama_7b_calc_yf_200",
    #     type=InternLM,
    #     model_type="LLAMA",
    #     path="s3://checkpoints_ssd_02/further_llama_7B_calc_yf/200",
    #     tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
    #     tokenizer_type='llama',
    #     module_path="/mnt/petrelfs/share_data/shaoyunfan/train_internlm/",
    #     model_config="/mnt/petrelfs/share_data/shaoyunfan/train_internlm/configs/further_llama_7B_calc_yf_eval.py",
    #     max_out_len=100,
    #     max_seq_len=2048,
    #     batch_size=16,
    #     run_cfg=dict(num_gpus=1, num_procs=1)
    # ),

    dict(
        abbr="copernicus_7b_v0_4_1_1000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.4.1/1000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/configs/copernicus_7b_v0.4.1.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_4_1_2000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.4.1/2000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/configs/copernicus_7b_v0.4.1.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_4_1_3000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.4.1/3000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/configs/copernicus_7b_v0.4.1.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_4_1_4000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.4.1/4000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/configs/copernicus_7b_v0.4.1.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_4_1_5000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.4.1/5000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/configs/copernicus_7b_v0.4.1.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
    dict(
        abbr="copernicus_7b_v0_5_1_1000",
        type=InternLM,
        model_type="LLAMA",
        path="s3://checkpoints_ssd_02/copernicus_7b_v0.5.1/1000",
        tokenizer_path='/mnt/petrelfs/share_data/yanhang/tokenizes/llama.model',
        tokenizer_type='llama',
        module_path="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/",
        model_config="/mnt/petrelfs/feizhaoye.dispatch/train_internlm_2/configs/copernicus_7b_v0.5.1.py",
        max_out_len=100,
        max_seq_len=2048,
        batch_size=16,
        run_cfg=dict(num_gpus=1, num_procs=1)
    ),
]
